import { readFile, readdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "../..",
);
const assets = path.join(root, "app/assets");
const classes = path.join(assets, "class_icons");
const output = path.join(root, "ikkinz/src/render/assets.generated.ts");

function dataUrl(bytes) {
  return `data:image/png;base64,${bytes.toString("base64")}`;
}

const expectedClassCodes = [
  "BER",
  "BRD",
  "BST",
  "CLR",
  "DRU",
  "ENC",
  "MAG",
  "MNK",
  "NEC",
  "PAL",
  "RNG",
  "ROG",
  "SHK",
  "SHM",
  "WAR",
  "WIZ",
];

const app = dataUrl(await readFile(path.join(assets, "app.png")));
const files = (await readdir(classes))
  .filter((file) => file.endsWith(".png"))
  .sort();
const icons = {};
for (const file of files) {
  icons[path.basename(file, ".png").toUpperCase()] = dataUrl(
    await readFile(path.join(classes, file)),
  );
}
const missing = expectedClassCodes.filter((code) => !icons[code]);
if (missing.length > 0) {
  throw new Error(
    `Missing required Stonemite class icons: ${missing.join(", ")}`,
  );
}

const source = `// Generated by scripts/generate-assets.mjs from app/assets. Do not edit.\nexport const APP_IMAGE = ${JSON.stringify(app)};\nexport const CLASS_IMAGES: Readonly<Record<string, string>> = ${JSON.stringify(icons, null, 2)};\n`;
await writeFile(output, source);
console.log(
  `Generated ${path.relative(root, output)} with ${files.length} class icons.`,
);
